simpleStatus:
  "OFF": 0
  "ON": 1

digitalStatus:
  "SNA": 0
  "OFF": 1
  "ON": 2

flag:
  "SNA": 0
  "CLEARED": 1
  "SET": 2

prechargeContactorState:
  "SNA": 0
  "OPEN": 1
  "PRECHARGE_CLOSED": 2
  "PRECHARGE_HVP_CLOSED": 3
  "HVP_CLOSED": 4

pm100dxSwitchStatus:
  "OFF": 0
  "ON": 1

pm100dxInputStatus:
  "FALSE": 0
  "TRUE": 1

pm100dxOutputState:
  "OFF": 0
  "ON": 1

pm100dxVsmState:
  "VSM_START": 0
  "PRECHARGE_INIT": 1
  "PRECHARGE_ACTIVE": 2
  "PRECHARGE_COMPLETE": 3
  "VSM_WAIT": 4
  "VSM_READY": 5
  "MOTOR_RUNNING": 6
  "BLINK_FAULT": 7
  "SHUTDOWN_IN_PROCESS": 14
  "RECYCLE_POWER_STATE": 15

pm100dxInverterState:
  "POWER_ON": 0
  "STOP": 1
  "OPEN_LOOP": 2
  "CLOSED_LOOP": 3
  "WAIT": 4
  "IDLE_RUN": 8
  "IDLE_STOP": 9

pm100dxActiveStatus:
  "ACTIVE": 1
  "INACTIVE": 0

pm100dxInverterRunMode:
  "TORQUE_MODE": 0
  "SPEED_MODE": 1

pm100dxEnableState:
  "DISABLED": 0
  "ENABLED": 1

pm100dxInverterActiveDischargeState:
  "DISCHARGE_DISABLED": 0
  "DISCHARGE_ENABLED_WAITING": 1
  "SPEED_CHECK": 2
  "DISCHARGE_OCCURRING": 3
  "DISCHARGE_COMPLETED": 4

pm100dxInverterCommandMode:
  "CAN_MODE": 0
  "VSM_MODE": 1

pm100dxBurstModelMode:
  "STALL": 0
  "HIGH_SPEED": 1

pm100dxInverterLockoutState:
  "CAN_BE_ENABLED": 0
  "CANNOT_BE_ENABLED": 1

# 0= Reverse if inverter enabled & 0= stopped if inverter disabled.
pm100dxDirectionCommand:
  "REVERSE": 0
  "FORWARD": 1

pm100dxBmsActive:
  "BMS_NOT_RECEIVED": 0
  "BMS_RECEIVED": 1

pm100dxIsLimited:
  "NOT_LIMITED": 0
  "LIMITED": 1

gpsDrStage:
  "UNKNOWN": 0
  "INIT": 1
  "COARSE": 2
  "STABLE": 3

gpsDynamicStatus:
  "UNKNOWN": 0
  "STATIC": 1
  "DYNAMIC": 2

imdState:
  "INIT": 0
  "HEALTHY": 1
  "UNHEALTHY": 2
  "FAULT": 3
  "ERROR": 4

faultStatus:
  "OK": 0
  "FAULT": 1

crashSensorState:
  "SNA": 0
  "OK": 1
  "CRASHED": 2
  "ERROR": 3

pedalState:
  SNA: 0
  OK: 1
  SHORTED: 2
  DISCONNECTED: 3

appsState:
  "SNA": 0
  "OK": 1
  "DISAGREEMENT": 2
  "ERROR": 3

bppcState:
  "SNA": 0
  "OK": 1
  "FAULT": 2
  "FAULT_LATCHED": 3
  "ERROR": 4

torqueManagerState:
  "SNA": 0
  "INACTIVE": 1
  "ACTIVE": 2
  "ERROR": 3

brakeLightState:
  "SNA": 0
  "OFF": 1
  "ON": 2
  "FAULT": 3

vehicleState:
  "INIT": 0
  "ON_GLV": 1
  "ON_HV": 2
  "TS_RUN": 3
  "SLEEP": 4

hsdState:
  "SNA": 0
  "OFF": 1
  "ON": 2
  "SW_FUSED": 3
  "OVERCURRENT": 4
  "OVERTEMP": 5
  "RETRY": 6
  "FAULT": 7

raceMode:
  "SNA": 0
  "PIT": 1
  "RACE": 2

tssiState:
  "SNA": 0
  "ON_GREEN": 1
  "ON_RED": 2

pm100dxEepromAddress:
  "RELAY_COMMAND": 1
  "GAMMA_ADJUST": 12
  "FAULT_CLEAR": 20
  "GAMMA_ADJUST_EEPROM": 152

pm100dxEepromRWCommand:
  "READ": 0
  "WRITE": 1

shutdownCircuitStatus:
  "SNA": 0
  "OPEN": 1
  "CLOSED": 2

gear:
  "SNA": 0
  "FORWARD": 1
  "REVERSE": 2

screenPage:
  "SNA": 0
  "HOME": 1
  "BUTTONS": 2
  "DATA": 3
  "CONFIG": 4
  "LAUNCH": 5

launchControlState:
  SNA: 0
  INACTIVE: 1
  HOLDING: 2
  SETTLING: 3
  PRELOAD: 4
  LAUNCH: 5
  REJECTED: 6
  ERROR: 7

tractionControlState:
  SNA: 0
  INACTIVE: 1
  ACTIVE: 2
  FAULT_SENSOR: 3
  ERROR: 4
  LOCKOUT: 5

sleepFollowerState:
  SNA: 0
  OK_TO_SLEEP: 1
  NOK_TO_SLEEP: 2
  ALARM: 3

screenAlerts:
  NONE: 0
  FAULT_MC: 1
  FAULT_VCFRONT: 2
  FAULT_VCREAR: 3
  FAULT_VCPDU: 4
  FAULT_BMSB: 5
  FAULT_GLV: 6
  FAULT_EM: 7
  REVERSE: 8
  CRASH: 9

screenWarnings:
  NONE: 0
  HOT_CELL: 1
  HOT_POWERTRAIN: 2
  LOW_CELL: 3
  LOW_GLV: 4
  CONTACTS_OPEN_IN_RUN: 5
  IMU_UNCALIBRATED: 6
  APPS_DISABLED: 7

configSelection:
  NONE: 0
  CALIB_DYNAMICS: 1
  VEHICLE_CONTROL: 2
