on: [push]
name: Build
jobs:
  build_and_upload:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rust
        with:
          target: ${{ matrix.target }}
      - name: Copy Binary and SHA256
        shell: bash
        run: |
          cp "./conUDS/target/${{ matrix.target }}/release/conUDS" "./conUDS/"
          export sha_short=$(git rev-parse --short "$GITHUB_SHA")
          [[ -z $sha_short ]] && sha_short="unknown"
          echo "sha_short=$sha_short" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v3
        with:
          name: conUDS_${{ env.sha_short }}
          path: |
            ./conUDS/assets
            ./conUDS/conUDS
          if-no-files-found: error
      - name: Generate Archive Checksum
        shell: bash
        run: |
          sha256sum ./conUDS/conUDS >> CHECKSUM
          sha256sum ./conUDS/assets/nodes.yml >> CHECKSUM
      - uses: actions/upload-artifact@v3
        with:
          name: CHECKSUM
          path: |
            ./CHECKSUM
          if-no-files-found: error
